version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" # RabbitMQ Management Console
      - "5672:5672"   # RabbitMQ Port

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "5090:5090"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq

  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    ports:
      - "6090:6090"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "7090:7090"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq